import io
import contextlib

def execute_script_with_variables(symbolic_names, script):
    # Create a dictionary to serve as the global namespace for exec
    local_namespace = {}

    # Add the symbolic names to the local namespace
    local_namespace.update(symbolic_names)

    # Capture the output
    output = io.StringIO()
    
    try:
        # Execute the script within the provided namespace and redirect stdout
        with contextlib.redirect_stdout(output):
            exec(script, {}, local_namespace)
    except Exception as e:
        # If an error occurs, return the exception message
        return f"An error occurred: {e}"

    # Get the output as a string
    result = output.getvalue()
    
    # Close the StringIO object
    output.close()
    
    return result

# Example usage:
symbolic_names = {
    'x': 10,
    'y': 20
}

script = '''
print(f"The sum of x and y is: {x + y}")
'''

output = execute_script_with_variables(symbolic_names, script)
print("Output generated by the script:")
print(output)