def execute_dynamic_code(code_string: str):
    """
    Executes a string of Python code dynamically using the exec() function.

    This function takes a string containing valid Python code and executes it.
    Any output generated by the code will be printed to the console. This includes
    values printed using the print() function within the executed code.

    Parameters:
    code_string (str): A string containing the Python code to execute.

    Usage:
    >>> execute_dynamic_code('print("Hello, World!")')
    Hello, World!

    >>> execute_dynamic_code('x = 5\\ny = 10\\nprint("The sum is:", x + y)')
    The sum is: 15

    Note:
    The exec() function does not return any value, so it's important that the
    executed code uses print() or similar functions to produce output.

    Warning:
    Be cautious when using exec() with untrusted input, as it can lead to security
    vulnerabilities.
    """
    # Execute the code contained in code_string
    exec(code_string)

# Example usages:
# execute_dynamic_code('print("Hello, World!")')
# execute_dynamic_code('x = 5\\ny = 10\\nprint("The sum is:", x + y)')